### ISSUE TITLE
ValueError: invalid literal for float(): 

### ISSUE THREAD

**Issue by soichih** [aarya22/app-tract-profile#2]
I am seeing a similar error message that I've reported on dipy-tract earlier.

```
/usr/local/lib/python2.7/dist-packages/dicom/__init__.py:53: UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
Traceback (most recent call last):
  File "/app/main.py", line 43, in <module>
    main()
  File "/app/main.py", line 22, in main
    dti_params = dti.fit_dti(data_file, data_bval, data_bvec, out_dir='.')
  File "/pyAFQ/AFQ/dti.py", line 54, in fit_dti
    b0_threshold=b0_threshold)
  File "/pyAFQ/AFQ/utils/models.py", line 49, in prepare_data
    bvals.append(np.loadtxt(bval_file))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1024, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 725, in floatconv
    return float(x)
ValueError: invalid literal for float(): 0,0,0,0,0,0,0,0,0,0,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,
Command exited with non-zero status 1
2.90user 1.70system 0:17.18elapsed 26%CPU (0avgtext+0avgdata 1059488maxresident)k
154042inputs+16outputs (350major+45700minor)pagefaults 0swaps
./_run.sh: 4: [: -eq: unexpected operator
```

**Comment by soichih** [comment]
I believe we've fixed this issue by making the app that's generating bvals to output in the standard (space delimited) format.
