### ISSUE TITLE
"Cannot find a streamline delimiter"

### ISSUE THREAD

**Issue by soichih** [aarya22/app-tract-profile#3]
I am currently seeing following error message - running with output from ensemble tracking app.

Traceback (most recent call last):
  File "/N/dc2/scratch/brlife/carbonate-workflows/59d521263485200024dd261a/59d521a23485200024dd262d/main.py", line 43, in <module>
    main()
  File "/N/dc2/scratch/brlife/carbonate-workflows/59d521263485200024dd261a/59d521a23485200024dd262d/main.py", line 35, in main
    tg = nib.streamlines.load(tracks).tractogram
  File "/N/u/aryaam/Karst/github_repos/nibabel/nibabel/streamlines/__init__.py", line 96, in load
    return tractogram_file.load(fileobj, lazy_load=lazy_load)
  File "/N/u/aryaam/Karst/github_repos/nibabel/nibabel/streamlines/tck.py", line 153, in load
    streamlines = ArraySequence(tck_reader)
  File "/N/u/aryaam/Karst/github_repos/nibabel/nibabel/streamlines/array_sequence.py", line 93, in __init__
    self.extend(iterable)
  File "/N/u/aryaam/Karst/github_repos/nibabel/nibabel/streamlines/array_sequence.py", line 238, in extend
    for e in elements:
  File "/N/u/aryaam/Karst/github_repos/nibabel/nibabel/streamlines/tck.py", line 417, in _read
    "Cannot find a streamline delimiter. This file"
nibabel.streamlines.tractogram_file.DataError: Cannot find a streamline delimiter. This file might be corrupted.

**Comment by francopestilli** [comment]
@aarya22 was this ever solved?

**Comment by skoudoro** [comment]
As you can see [here](https://github.com/brain-life/app-ensembletracking/blob/1.1/ensemble_tck_generator.m#L26) @soichih, @kitchell is using a space as a delimiter to concatenate several streamlines files. 
I wonder if it is a standard way to do it and if this newly generated track file will work with Mrtrix too.

Instead of doing it manually and to avoid this kind of error, I suggest using `nibabel` or `Mrtrix3` to do this kind of task. No idea of the way to do it with `Mrtrix`. With `nibabel`, you just need to use `nib.streamlines.load` for loading a track file. This will return you a `Streamlines`object. Then, `streamlines.append` should do the work.

It will good to check if every apps generate data in the correct ways. Consistency is important 😄
